#!/bin/bash
set -e

command -v wget >/dev/null 2>&1 || { echo >&2 "I require wget but it's not installed.  Aborting."; exit 1; }

FTP="https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/"
PATTERN="[0-9][0-9]\.[0-9][0-9]\.[0-9]"
CONTENT=$(wget $FTP -q -O -)
VERSIONS=$(grep -o $PATTERN <<< $CONTENT | sort -u)
LATEST=$(grep $PATTERN <<< $VERSIONS | tr " " "\n" | tail -1)
VERSION=$LATEST
DISTRO=$(hostnamectl | grep -oi "bionic\|xenial\|stretch\|centos7" | head -1)


while getopts v: option
do
case "${option}"
in
v) 
	VERSION=${OPTARG};
	if [[ $VERSIONS != *"${VERSION}"* ]]; 
	then
		echo "Version Unavailable..."
		echo "Try installing one of the following versions:"
		echo $(grep -o $PATTERN <<< $VERSIONS)
		echo ""
		exit
	fi
esac
done

APPENDIX=""
if [[ $VERSION == "${LATEST}" ]];
then
	APPENDIX="<latest>"
fi

printf "\n ===== [INSTALLATION PARAMETERS] >>>\n\n"
echo "DISTRO:   ${DISTRO}"
echo "VERSION:  ${VERSION} ${APPENDIX}"
printf "\n------------------------------------\n"





# Installation for UBUNTU distros
if [[ "bionic xenial" == *"${DISTRO}"* ]];
then
	DOCKER="docker-ce_${VERSION}~3-0~ubuntu-${DISTRO}_ppc64el.deb"
	DOCKER_CLI="docker-ce-cli_${VERSION}~3-0~ubuntu-${DISTRO}_ppc64el.deb"

	sudo apt update
	printf "\n============== [FETCHING PACKAGES] ===============\n"
	wget ${FTP}version-$VERSION/ubuntu-$DISTRO/$DOCKER_CLI
	wget ${FTP}version-$VERSION/ubuntu-$DISTRO/$DOCKER
	printf "\n============= [INSTALLING PACKAGES] ==============\n"
	sudo apt install -y --allow-downgrades ./$DOCKER_CLI
	sudo apt install -y --allow-downgrades ./$DOCKER
	rm $DOCKER $DOCKER_CLI
	printf "\n=============== [CHECKING VERSION] ===============\n"
	sudo docker version | grep -B 2 version
	printf "\n============= [TESTING INSTALLATION] =============\n"
	sudo docker run hello-world
	printf "\n====================== [DONE] ====================\n" 
	printf "Everything seems to be working fine\n"
	exit
fi




# Installation for CENTOS distros
if [[ "centos7" == *"${DISTRO}"* ]];
then
	DOCKER="docker-ce-${VERSION}-3.el7.ppc64le.rpm"
	DOCKER_CLI="docker-ce-cli-${VERSION}-3.el7.ppc64le.rpm"

	sudo yum install -y epel-release wget
	sudo yum update -y

	wget ${FTP}version-${VERSION}/centos/$DOCKER_CLI
	wget ${FTP}version-${VERSION}/centos/$DOCKER

	if [[ $VERSION < $(sudo docker --version | grep -o $PATTERN) ]];
	then
		echo "DOWNGRADING..."
		sudo yum downgrade -y ./$DOCKER
		sudo yum downgrade -y ./$DOCKER_CLI
	else
		sudo yum install -y ./$DOCKER_CLI
		sudo yum install -y ./$DOCKER
	fi
	
	rm $DOCKER_CLI $DOCKER
	sudo systemctl restart docker
	sudo docker version | grep -B 2 version

	sudo docker run hello-world
	exit
fi




# Installation for Debian distros
if [[ "stretch" == *"${DISTRO}"* ]];
then
	DOCKER="docker-ce_${VERSION}~3-0~debian-${DISTRO}_ppc64el.deb"
	DOCKER_CLI="docker-ce-cli_${VERSION}~3-0~debian-${DISTRO}_ppc64el.deb"
	
	if [[ $(apt policy libseccomp2 | grep -oP '(?<=Installed: )(.*)') < "2.4.2-2" ]];
	then
		wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.2-2_ppc64el.deb
		sudo apt install -y ./libseccomp2_2.4.2-2_ppc64el.deb
		rm libseccomp2_2.4.2-2_ppc64el.deb
	fi

	if [[ $(apt policy containerd | grep -oP '(?<=Installed: )(.*)') < "1.3" ]];
	then
		wget http://ftp.us.debian.org/debian/pool/main/c/containerd/containerd_1.3.2~ds1-3_ppc64el.deb
		sudo apt install -y ./containerd_1.3.2~ds1-3_ppc64el.deb
		rm containerd_1.3.2~ds1-3_ppc64el.deb
	fi

	if [[ $(apt policy runc | grep -oP '(?<=Installed: )(.*)') < "1.0.0~rc10+dfsg1-1" ]];
	then
		wget http://ftp.us.debian.org/debian/pool/main/r/runc/runc_1.0.0~rc10+dfsg1-1_ppc64el.deb
		sudo apt install -y ./runc_1.0.0~rc10+dfsg1-1_ppc64el.deb
		rm runc_1.0.0~rc10+dfsg1-1_ppc64el.deb
	fi

	wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-${VERSION}/debian-${DISTRO}/$DOCKER_CLI
	wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/version-${VERSION}/debian-${DISTRO}/$DOCKER
	sudo apt install -y --allow-downgrades ./$DOCKER_CLI ./$DOCKER
	rm $DOCKER $DOCKER_CLI

	sudo systemctl restart docker
	sudo docker version | grep -B 2 version

	sudo docker run hello-world
	exit
fi

